### ISSUE TITLE
Would like to add Path Finding Algorithms.

### ISSUE THREAD

**Issue by Sandeep-1507** [Romi904/Durmello#127]
I would like to add a path finding algorithms folder which would include a major graph traversal algorithms like

1. BFS
2. DFS
3. Dijkstra's Algorithm
4. Astar Algorithm
These would be implemented using python and this would also include a image as graph over which this would be implemented and will find specific coloured parts.

**Comment by Romi904** [comment]
Nope, DSA contributions are excluded.

**Comment by Romi904** [comment]
anything related DSA are excluded.

**Comment by Romi904** [comment]
But you can contribute here
https://github.com/Romi904/Lemon_Juice

**Comment by Romi904** [comment]
[![Contact me](https://img.shields.io/badge/Gmail-D14836?style=for-the-badge&logo=gmail&logoColor=white)(https://github.com/Romi904/Lemon_Juice)

**Comment by Romi904** [comment]
Ya I know, but I don't want to take risk🤔.
but,
okay Iam opening the issue contribute.👍

**Comment by Sandeep-1507** [comment]
Thanks:)
