### ISSUE TITLE
would like to add python snake and apple game

### ISSUE THREAD

**Issue by rahulranjan74** [Romi904/Durmello#130]
I would like to add python snake and apple game

**Comment by Romi904** [comment]
### ATTENTION 🚨🚨🚨
Don’t Forget To Follow Me On Github , and Add Your Name In `_contributing.md` if not found your name in `_contributing.md` it should be Labelled as **SPAM**.
STAR 🌟 this REPO for future HacktoberFest.

**Comment by Romi904** [comment]
okay I have Assigned you.

**Comment by rahulranjan74** [comment]
Thanks!

**Comment by Romi904** [comment]
Don't forget to follow and star this repo for future hacktober.

**Comment by rahulranjan74** [comment]
done
