### ISSUE TITLE
LeetCode problem 1530. Number of Good Leaf Nodes Pairs solution

### ISSUE THREAD

**Issue by shubhamrawat090** [Romi904/Durmello#142]
I would like to submit my solution for the above mentioned problem with comments explaining my logic as well.
This is the link here https://leetcode.com/problems/number-of-good-leaf-nodes-pairs/description/
@Romi904 Please assign this to me.

**Comment by Romi904** [comment]
### ATTENTION 🚨🚨🚨
Don’t Forget To Follow Me On Github , and Add Your Name In `_contributing.md` if not found your name in `_contributing.md` it should be Labelled as **SPAM**.
STAR 🌟 this REPO for future HacktoberFest.

**Comment by Romi904** [comment]
DSA problems are prohibited.
