### ISSUE TITLE
Coin Toss

### ISSUE THREAD

**Issue by workspace-utkarsh** [Romi904/Durmello#147]
Can you assign me this task to create a python program to generate randomly heads or tails on running the script.

**Comment by Romi904** [comment]
### ATTENTION 🚨🚨🚨
Don’t Forget To Follow Me On Github , and Add Your Name In `_contributing.md` if not found your name in `_contributing.md` it should be Labelled as **SPAM**.
STAR 🌟 this REPO for future HacktoberFest.

**Comment by Romi904** [comment]
No, same things already exist on the repo.
