### ISSUE TITLE
XOR of natural numbers from 1 to n

### ISSUE THREAD

**Issue by RoyCoding8** [Romi904/Durmello#166]
Hello @Romi904, I wanted to add the program for computing the XOR of all natural numbers from 1 to n. Please assign it to me.

**Comment by Romi904** [comment]
### ATTENTION 🚨🚨🚨
Don’t Forget To Follow Me On Github , and Add Your Name In `_contributing.md` if not found your name in `_contributing.md` it should be Labelled as **SPAM**.
STAR 🌟 this REPO for future HacktoberFest.
<a href="https://t.me/hacktoberfest022"><img src="https://img.shields.io/badge/CHAT_US-06283D?style=for-the-badge&logo=telegram" alt=""/></a>

**Comment by Romi904** [comment]
DSA's are strictly prohibited.
