### ISSUE TITLE
Backtracking 

### ISSUE THREAD

**Issue by aditi10701** [Romi904/Durmello#17]
Questions like backtracking can also be added. Questions like
1) Sudoku Solver
2) N Queen Problem
3)  Rat in a Maze
4) M coloring Problem
Kindly assign me this issue I want to work on it.

**Comment by Romi904** [comment]
Okay.
I assigned you. :_

**Comment by TurboPug2101** [comment]
please assign me this.

**Comment by Romi904** [comment]
@TurboPug2101 Make new PR or issue

**Comment by TurboPug2101** [comment]
Hi,i would like to add the following questions to the backtracking questions list:
Print all Hamiltonian paths present in a graph.
Magnet Puzzle

please assign me this.

**Comment by Romi904** [comment]
okay, ASSIGNED @TurboPug2101
