### ISSUE TITLE
updating readme.md file of this repo

### ISSUE THREAD

**Issue by AdityaMathur25** [Romi904/Durmello#184]
hi i want to update readme.md file of this repo and add some more content about opensource their please assing me this issue :)

i will be happy to contribute

**Comment by Romi904** [comment]
Assigned

**Comment by AdityaMathur25** [comment]
Please merge my pr 

**Pr tittle : updated documentation for the repo

Pr Number :  #191**

**Comment by Romi904** [comment]
Done

**Comment by Romi904** [comment]
### ATTENTION 🚨🚨🚨
Don’t Forget To Follow Me On Github , and Add Your Name In `_contributing.md` if not found your name in `_contributing.md` it should be Labelled as **SPAM**.
STAR 🌟 this REPO for future HacktoberFest.
<a href="https://t.me/hacktoberfest022"><img src="https://img.shields.io/badge/CHAT_US-06283D?style=for-the-badge&logo=telegram" alt=""/></a>
