### ISSUE TITLE
I would like to add the folllowing Problems on Dynamic Programming

### ISSUE THREAD

**Issue by Koustubh-Mane1** [Romi904/Durmello#89]
Word Break - https://leetcode.com/problems/word-break/
Longest Increasing Subsequence - https://leetcode.com/problems/longest-increasing-subsequence/
Maximum Product Subarray - https://leetcode.com/problems/maximum-product-subarray/

**Comment by Romi904** [comment]
Nah. Already Peoples are contributed in this domain.

**Comment by Romi904** [comment]
star this repo for future hacktober and follow me
